"""Participant abstraction for the multi_agent conference framework.

Three concrete participant types ship today:

* :class:`LLMParticipant` (Option α — prompt-text) — the prior conversation
  is rendered into the system prompt as text. Best for short conferences;
  matches what the legacy ``risk_debate`` flow does. Implements
  :class:`Participant`'s ``async speak`` Protocol.
* :class:`LLMMessageParticipant` (Option β — message-thread) — the prior
  conversation is forwarded as a ``BaseMessage`` thread. The system prompt
  holds only the role description; better for long conferences (prompt-cache
  reuse). Implements :class:`Participant`.
* :class:`AgentParticipant` — wraps a compiled muffin agent with persistent
  per-thread state. The agent is added as a parent-graph node (via a thin
  ``prep → agent → extract`` subgraph generated by the framework); the
  agent's internal tool calls / intermediate AIMessages stay isolated from
  conference state. Does NOT implement the ``Participant`` Protocol's
  ``speak`` method — invoked natively by LangGraph instead.

The framework normalises state before calling :meth:`Participant.speak`:
the shared conversation is at ``state["messages"]`` (a ``list[BaseMessage]``).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage
from langchain_core.runnables import RunnableConfig
from langgraph.graph.state import CompiledStateGraph

from ..model_config import ModelConfiguration, Role
from ..prompts import render_template
from ._formatters import last_opposing_message, render_messages_chronological


@runtime_checkable
class Participant(Protocol):
    """One single-LLM-call speaker in a conference.

    Implemented by :class:`LLMParticipant` and :class:`LLMMessageParticipant`.
    :class:`AgentParticipant` does NOT implement this Protocol — it's added
    as a parent-graph node by the framework instead.
    """

    name: str

    async def speak(
        self, state: dict[str, Any], config: RunnableConfig
    ) -> str:
        """Produce one turn of free-text content for this participant."""
        ...


@dataclass
class LLMParticipant:
    """Participant that issues one LLM call per turn (Option α — prompt-text).

    Template vars made available to ``system_prompt_template``:

    * ``transcript`` — chronological text rendering of the shared
      conversation via :func:`render_messages_chronological`.
    * ``last_opposing_message`` — most recent ``BaseMessage`` by a
      non-self speaker, or ``None`` on the opening turn.
    * every other key in ``state``.
    """

    name: str
    system_prompt_template: str
    llm_role: Role = "reasoner"
    user_prompt: str = "Take your turn now."

    async def speak(
        self, state: dict[str, Any], config: RunnableConfig
    ) -> str:
        """Render the role prompt + transcript and return one LLM turn."""
        messages: list[BaseMessage] = state.get("messages") or []
        llm = ModelConfiguration.get_chat_model_for_role(config, self.llm_role)
        template_vars: dict[str, Any] = {
            **state,
            "transcript": render_messages_chronological(messages),
            "last_opposing_message": last_opposing_message(messages, self.name),
        }
        prompt = render_template(self.system_prompt_template, **template_vars)
        response = await llm.ainvoke(
            [SystemMessage(prompt), HumanMessage(self.user_prompt)]
        )
        return str(response.content).strip()


@dataclass
class LLMMessageParticipant:
    """Participant that forwards the shared conversation as a message thread (Option β).

    The system prompt holds only the participant's role description (no
    transcript). Each prior message in shared ``state["messages"]`` becomes
    either an ``AIMessage`` (if its ``name`` matches this participant's
    own) or a ``HumanMessage`` prefixed with ``[<speaker>]:`` for any
    other speaker. Speaker tagging is via content prefix (portable across
    OpenAI / Anthropic / OpenRouter — the ``name`` attribute is preserved
    on the BaseMessage object but is not universally transmitted to the
    model).
    """

    name: str
    system_prompt_template: str
    llm_role: Role = "reasoner"
    user_prompt: str = "Take your turn now."

    async def speak(
        self, state: dict[str, Any], config: RunnableConfig
    ) -> str:
        """Materialise the conversation as messages and return one LLM turn."""
        messages: list[BaseMessage] = state.get("messages") or []
        llm = ModelConfiguration.get_chat_model_for_role(config, self.llm_role)
        prompt = render_template(self.system_prompt_template, **state)
        history: list[AIMessage | HumanMessage] = [
            AIMessage(m.content) if (m.name or "") == self.name
            else HumanMessage(
                f"[{m.name or 'speaker'}]: {m.content}",
                name=m.name,
            )
            for m in messages
        ]
        response = await llm.ainvoke(
            [SystemMessage(prompt), *history, HumanMessage(self.user_prompt)]
        )
        return str(response.content).strip()


@dataclass
class AgentParticipant:
    """Participant backed by a compiled muffin agent with persistent thread state.

    The wrapped agent MUST be built with a checkpointer (e.g.
    ``MuffinAgentBuilder(...).with_checkpointer(InMemorySaver()).build_react_agent()``)
    so its internal state (prior tool results, intermediate AIMessages,
    ReAct scratch) persists across turns within a single conference run.

    `build_conference_graph` adds a small wrapper subgraph as a parent
    graph node::

        bob (subgraph) :  prep -> bob_agent -> extract

    where ``bob_agent`` IS the user's compiled agent added as a graph node
    natively. ``prep`` slices ``state["messages"]`` by
    ``state["agent_cursors"][name]`` (using ``BaseMessage.id``) to give the
    agent only NEW messages since its last turn. ``extract`` tags the
    agent's final AIMessage with ``name=self.name``, clears the subgraph's
    messages buffer, and updates the cursor.

    Net effect on parent state per turn: ONE new ``AIMessage`` appended
    (tagged with this agent's name), cursor advanced. The agent's
    internal tool calls / intermediate AIMessages live in the agent's own
    per-thread checkpoint and never propagate to parent state.

    Unlike :class:`LLMParticipant`, this class does NOT implement
    :meth:`Participant.speak` — it's wired into the conference graph as a
    subgraph node rather than invoked through the Protocol.
    """

    name: str
    agent: CompiledStateGraph
    user_prompt: str = "Take your turn now."
